name: Generate Snake

on:
  schedule: # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: GodyRacks
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit generated SVG
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push

