name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        id: snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push generated SVG
        if: steps.snake.outputs.success == 'true'  # Ensure the snake generation was successful
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
